CREATE TABLE tbc_histpac (
	HistpacNro DECIMAL(10,0) NOT NULL,
	HistpacFec INTEGER NOT NULL,
	HistpacH INTEGER NOT NULL,
	HistpacM INTEGER NOT NULL,
	HistpacR INTEGER NOT NULL,
	HistpacE INTEGER NOT NULL,
	HistpacEspfir INTEGER NOT NULL,
	HistpacNro1 DECIMAL(10,0) NOT NULL,
	HistpacFec1 INTEGER NOT NULL,
	HistpacNro2 DECIMAL(10,0) NOT NULL,
	HistpacEspfir1 INTEGER NOT NULL,
	HistpacMedfir INTEGER,
	HistpacMotivo DECIMAL(10,0),
	HistpacEstudi DECIMAL(10,0),
	HistpacHoraSobre INTEGER,
	HistpacHFinal INTEGER,
	HistpacMFinal INTEGER,
	HistpacRFinal INTEGER,
	HistpacDiagno CHAR(28) NOT NULL,
	HistpacPatolo INTEGER,
	HistpacTratam DECIMAL(10,0),
	HistpacMedfirNya CHAR(30) NOT NULL,
	HistpacMedfirMat INTEGER,
	HistpacHAtenc INTEGER,
	HistpacMAtenc INTEGER,
	HistpacRAtenc INTEGER,
	HistpacDeriva INTEGER,
	HistpacDerivaDs INTEGER,
	HistpacDerivaSec CHAR(11) NOT NULL,
	HistpacObra INTEGER,
	HistpacPPlan CHAR(10) NOT NULL,
	HistpacPlan CHAR(1) NOT NULL,
	HistpacAfil CHAR(15) NOT NULL,
	HistpacPedAmbula INTEGER,
	HistpacConsHiv CHAR(1) NOT NULL,
	HistpacInterconsu INTEGER,
	HistpacEntregado INTEGER,
	HistpacCtro INTEGER,
	HistpacYodo CHAR(1) NOT NULL,
	HistpacCancd INTEGER,
	CONSTRAINT X_1_2_3_4_5_6 PRIMARY KEY (HistpacNro,HistpacFec,HistpacH,HistpacM,HistpacR,HistpacE)
);
CREATE INDEX X_7_8_9 ON tbc_histpac (HistpacEspfir,HistpacNro1,HistpacFec1);
CREATE INDEX X_8_9 ON tbc_histpac (HistpacNro1,HistpacFec1);
CREATE INDEX X_A_B ON tbc_histpac (HistpacNro2,HistpacEspfir1);

CREATE TABLE tbc_reservas (
	ReservasEsp INTEGER,
	ReservasMed INTEGER,
	ReservasFech INTEGER,
	ReservasHora INTEGER,
	ReservasMed1 INTEGER,
	ReservasEsp1 INTEGER,
	ReservasFech1 INTEGER,
	ReservasHora1 INTEGER,
	ReservasTipo CHAR(1) NOT NULL,
	ReservasEsp2 INTEGER,
	ReservasMed2 INTEGER,
	ReservasFech2 INTEGER,
	ReservasHora2 INTEGER,
	ReservasEsta INTEGER,
	ReservasFech3 INTEGER,
	ReservasMed3 INTEGER,
	ReservasEsp3 INTEGER,
	ReservasHora3 INTEGER,
	ReservasFech6 INTEGER,
	ReservasMed6 INTEGER,
	ReservasEsp6 INTEGER,
	ReservasHora6 INTEGER,
	ReservasHiscli DECIMAL(10,0),
	ReservasFech5 INTEGER,
	ReservasHora5 INTEGER,
	ReservasObra INTEGER,
	ReservasObrpla CHAR(10) NOT NULL,
	ReservasNroben CHAR(15) NOT NULL,
	ReservasNumeroFc INTEGER,
	ReservasLetraFc CHAR(1) NOT NULL,
	ReservasMedsol INTEGER,
	ReservasTipsol CHAR(1) NOT NULL,
	ReservasAtendi INTEGER,
	ReservasPrimeraVez INTEGER,
	ReservasTipser INTEGER,
	ReservasIPedido INTEGER,
	ReservasHoraAtenc INTEGER,
	ReservasHoraSobre INTEGER,
	ReservasOpera INTEGER,
	ReservasTipoOpera INTEGER,
	ReservasFechaPed INTEGER,
	ReservasHoraPed INTEGER,
	ReservasSexo INTEGER,
	ReservasOperaConf INTEGER,
	ReservasTipoOperaConf INTEGER,
	ReservasCron INTEGER,
	ReservasLlamadaEstado CHAR(1) NOT NULL,
	ReservasLlamadaDestino INTEGER,
	ReservasIva INTEGER,
	ReservasTipserCef INTEGER,
	ReservasEstaCef INTEGER,
	ReservasFechCef INTEGER,
	ReservasAtendiCef INTEGER,
	ReservasHoraCef INTEGER,
	ReservasServicio INTEGER,
	ReservasMedicab CHAR(13) NOT NULL,
	ReservasAutoriza CHAR(12) NOT NULL,
	ReservasConsu INTEGER,
	ReservasPartEspe INTEGER,
	ReservasConEstudio INTEGER,
	ReservasETipoEstudio_10 INTEGER,
	ReservasETipoEstudio_9 INTEGER,
	ReservasETipoEstudio_8 INTEGER,
	ReservasETipoEstudio_7 INTEGER,
	ReservasETipoEstudio_6 INTEGER,
	ReservasETipoEstudio_5 INTEGER,
	ReservasETipoEstudio_4 INTEGER,
	ReservasETipoEstudio_3 INTEGER,
	ReservasETipoEstudio_2 INTEGER,
	ReservasETipoEstudio_1 INTEGER,
	ReservasMenorAcom INTEGER,
	ReservasFechaConf INTEGER,
	ReservasHoraConf INTEGER,
	ReservasNordEges CHAR(12) NOT NULL,
	CONSTRAINT X_1_2_3_4_0 PRIMARY KEY (ReservasEsp,ReservasMed,ReservasFech,ReservasHora)
);
CREATE UNIQUE INDEX X13141516_0 ON tbc_reservas (ReservasFech6,ReservasMed6,ReservasEsp6,ReservasHora6);
CREATE INDEX X171819_0 ON tbc_reservas (ReservasHiscli,ReservasFech5,ReservasHora5);
CREATE INDEX X1D1E_0 ON tbc_reservas (ReservasNumeroFc,ReservasLetraFc);
CREATE INDEX X292A_0 ON tbc_reservas (ReservasFechaPed,ReservasHoraPed);
CREATE INDEX X3233343536_0 ON tbc_reservas (ReservasTipserCef,ReservasEstaCef,ReservasFechCef,ReservasAtendiCef,ReservasHoraCef);
CREATE UNIQUE INDEX X_5_6_7_8_0 ON tbc_reservas (ReservasMed1,ReservasEsp1,ReservasFech1,ReservasHora1);
CREATE UNIQUE INDEX X_9_A_B_C_D_0 ON tbc_reservas (ReservasTipo,ReservasEsp2,ReservasMed2,ReservasFech2,ReservasHora2);
CREATE UNIQUE INDEX X_E_F101112_0 ON tbc_reservas (ReservasEsta,ReservasFech3,ReservasMed3,ReservasEsp3,ReservasHora3);



