CREATE DATABASE asistencial;
USE asistencial;
CREATE TABLE tbc_histpac (
	HistpacNro DECIMAL(10,0) NOT NULL,
	HistpacFec INTEGER NOT NULL,
	HistpacH INTEGER NOT NULL,
	HistpacM INTEGER NOT NULL,
	HistpacR INTEGER NOT NULL,
	HistpacE INTEGER NOT NULL,
	HistpacEspfir INTEGER NOT NULL,
	HistpacNro1 DECIMAL(10,0) NOT NULL,
	HistpacFec1 INTEGER NOT NULL,
	HistpacNro2 DECIMAL(10,0) NOT NULL,
	HistpacEspfir1 INTEGER NOT NULL,
	HistpacMedfir INTEGER,
	HistpacMotivo DECIMAL(10,0),
	HistpacEstudi DECIMAL(10,0),
	HistpacHoraSobre INTEGER,
	HistpacHFinal INTEGER,
	HistpacMFinal INTEGER,
	HistpacRFinal INTEGER,
	HistpacDiagno CHAR(28) NOT NULL,
	HistpacPatolo INTEGER,
	HistpacTratam DECIMAL(10,0),
	HistpacMedfirNya CHAR(30) NOT NULL,
	HistpacMedfirMat INTEGER,
	HistpacHAtenc INTEGER,
	HistpacMAtenc INTEGER,
	HistpacRAtenc INTEGER,
	HistpacDeriva INTEGER,
	HistpacDerivaDs INTEGER,
	HistpacDerivaSec CHAR(11) NOT NULL,
	HistpacObra INTEGER,
	HistpacPPlan CHAR(10) NOT NULL,
	HistpacPlan CHAR(1) NOT NULL,
	HistpacAfil CHAR(15) NOT NULL,
	HistpacPedAmbula INTEGER,
	HistpacConsHiv CHAR(1) NOT NULL,
	HistpacInterconsu INTEGER,
	HistpacEntregado INTEGER,
	HistpacCtro INTEGER,
	HistpacYodo CHAR(1) NOT NULL,
	HistpacCancd INTEGER,
	CONSTRAINT X_1_2_3_4_5_6 PRIMARY KEY (HistpacNro,HistpacFec,HistpacH,HistpacM,HistpacR,HistpacE)
);
CREATE INDEX X_7_8_9 ON Asistencial.tbc_histpac (HistpacEspfir,HistpacNro1,HistpacFec1);
CREATE INDEX X_8_9 ON Asistencial.tbc_histpac (HistpacNro1,HistpacFec1);
CREATE INDEX X_A_B ON Asistencial.tbc_histpac (HistpacNro2,HistpacEspfir1);

CREATE TABLE Asistencial.tbc_guardia (
	Guar_HistClinica DECIMAL(10,0) NOT NULL,
	Guar_FechaIngreso INTEGER NOT NULL,
	Guar_HoraIngreso INTEGER NOT NULL,
	Guar_Especialidad INTEGER NOT NULL,
	Guar_Estado INTEGER NOT NULL,
	Guar_FechaIngreso1 INTEGER NOT NULL,
	Guar_HoraIngreso1 INTEGER NOT NULL,
	Guar_HistClinica1 DECIMAL(10,0) NOT NULL,
	Guar_Especialidad1 INTEGER NOT NULL,
	Guar_Estado1 INTEGER NOT NULL,
	Guar_FechaIngreso3 INTEGER NOT NULL,
	Guar_HoraIngreso3 INTEGER NOT NULL,
	Guar_Especialidad3 INTEGER NOT NULL,
	Guar_Estado3 INTEGER NOT NULL,
	Guar_ApeNom CHAR(35) NOT NULL,
	Guar_Obra INTEGER,
	Guar_Plan CHAR(10) NOT NULL,
	Guar_Nroben CHAR(15) NOT NULL,
	Guar_Medico INTEGER,
	Guar_TipoMed INTEGER,
	Guar_Diagnostico INTEGER,
	Guar_FechaAlta INTEGER,
	Guar_HoraAlta INTEGER,
	Guar_Turno INTEGER,
	Guar_PrimeraVez INTEGER,
	Guar_EspMed INTEGER,
	Guar_HoraAtenc INTEGER,
	Guar_LetraFc CHAR(1) NOT NULL,
	Guar_NumeFc INTEGER,
	Guar_TipoOperador INTEGER,
	Guar_Operador INTEGER,
	Guar_Deriva INTEGER,
	Guar_DerivaSec INTEGER,
	Guar_Habita INTEGER,
	Guar_Cama CHAR(1) NOT NULL,
	Guar_Pamifup INTEGER,
	Guar_Anestesia INTEGER,
	Guar_Ctro INTEGER,
	Guar_Reingreso INTEGER,
	Guar_FechaCama INTEGER,
	Guar_HoraCama INTEGER,
	Guar_FechaEpic INTEGER,
	Guar_MenorAcom INTEGER,
	Guar_OpeTipReingreso INTEGER,
	Guar_OpeLegReingreso INTEGER,
	Guar_OpeTipCama INTEGER,
	Guar_OpeLegCama INTEGER,
	Guar_EstadoFebril INTEGER,
	Guar_QuienAnula INTEGER,
	Guar_OtrCtro INTEGER,
	GuarIva INTEGER,
	GuarPresuFac INTEGER,
	GuarNivel INTEGER,
	GuarMedicab CHAR(7) NOT NULL,
	GuarNropres INTEGER,
	CONSTRAINT X_1_2_3 PRIMARY KEY (Guar_HistClinica,Guar_FechaIngreso,Guar_HoraIngreso)
);
CREATE INDEX X_4_5_6_7 ON Asistencial.tbc_guardia (Guar_Especialidad,Guar_Estado,Guar_FechaIngreso1,Guar_HoraIngreso1);
CREATE INDEX X_8_9_A ON Asistencial.tbc_guardia (Guar_HistClinica1,Guar_Especialidad1,Guar_Estado1);
CREATE INDEX X_B_C_D_E ON Asistencial.tbc_guardia (Guar_FechaIngreso3,Guar_HoraIngreso3,Guar_Especialidad3,Guar_Estado3);

CREATE DATABASE desal;
USE desal;
CREATE TABLE tbl_hist_txt (
	ht_histclin numeric(10) NOT NULL,
	ht_fecha numeric(8) NOT NULL,
	ht_hora numeric(8) NOT NULL,
	ht_entrada numeric(1) NOT NULL,
	ht_motivo varchar(7800) NULL,
	ht_tratamiento varchar(7800) NULL,
	ht_estudios varchar(7800) NULL,
	CONSTRAINT pk_hist_txt PRIMARY KEY (ht_histclin, ht_fecha, ht_hora, ht_entrada)
);
